name: Deploy to server
on:
  push:
    branches: [production]

jobs:
  job_one:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          script: |
            cd ~/front/
            git stash
            git pull origin production
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v16.17.0/bin/
            source ~/.bashrc
            cd app/
            yarn build
            pm2 delete front
            pm2 start "yarn start" --name front
